USE smart_job_portal;

INSERT INTO users (name, email, password, role, skills, resume)
SELECT 'Seed Company', 'seed-company@smartjobportal.local', '$2b$10$8jQ0p2xQv9pWlFf3G8tQ8e3xIY8iK9oP8j4Nw5sQ0m7uR6yT1aB2C', 'company', 'Hiring, Recruitment', ''
WHERE NOT EXISTS (
  SELECT 1 FROM users WHERE email = 'seed-company@smartjobportal.local'
);

SET @seed_company_id = (SELECT id FROM users WHERE email = 'seed-company@smartjobportal.local' LIMIT 1);

INSERT INTO jobs (category, title, company, location, type, skills_required, salary, description, posted_by) VALUES
('Fresher Jobs','Junior Software Developer','TCS','Indore','job','Java,SQL','4.2 LPA','Entry-level software development role for fresh graduates working on Java and SQL-based applications.',@seed_company_id),
('Fresher Jobs','Graduate Trainee Engineer','Infosys','Bangalore','job','Java,Spring','4.5 LPA','Graduate trainee role focused on backend services and enterprise application support.',@seed_company_id),
('Fresher Jobs','Associate Developer','Wipro','Hyderabad','job','Python,SQL','4.3 LPA','Join the development team to build and maintain internal business applications.',@seed_company_id),
('Fresher Jobs','Software Engineer Trainee','Accenture','Pune','job','JavaScript,Node','4.6 LPA','Support product development and work on Node.js driven web services.',@seed_company_id),
('Fresher Jobs','Junior Backend Developer','Tech Mahindra','Noida','job','Java,MySQL','4.4 LPA','Assist in backend API development and MySQL query optimization.',@seed_company_id),
('Fresher Jobs','IT Support Engineer','HCL','Delhi','job','Networking','3.8 LPA','Handle entry-level IT support, troubleshooting, and network issue resolution.',@seed_company_id),
('Fresher Jobs','Software Tester','Capgemini','Mumbai','job','Testing','4.0 LPA','Execute manual and functional testing for enterprise applications.',@seed_company_id),
('Fresher Jobs','Junior Web Developer','Mindtree','Bangalore','job','HTML,CSS,JS','4.1 LPA','Build responsive web interfaces and support frontend development tasks.',@seed_company_id),
('Fresher Jobs','Data Analyst Trainee','Cognizant','Hyderabad','job','Python,Excel','4.2 LPA','Analyze business data and prepare reports using Python and Excel.',@seed_company_id),
('Fresher Jobs','Junior QA Engineer','IBM','Pune','job','Manual Testing','4.3 LPA','Support quality assurance cycles with test planning and bug reporting.',@seed_company_id),
('Fresher Jobs','Graduate Developer','L&T Infotech','Mumbai','job','Java','4.4 LPA','Work with senior engineers to develop and maintain Java-based systems.',@seed_company_id),
('Fresher Jobs','Software Support Engineer','Zoho','Chennai','job','SQL','4.0 LPA','Provide software support and handle SQL-based troubleshooting tasks.',@seed_company_id),
('Fresher Jobs','Junior Application Developer','Oracle','Bangalore','job','Java','4.8 LPA','Entry-level application development role in enterprise Java systems.',@seed_company_id),
('Fresher Jobs','IT Associate','Amazon','Hyderabad','job','Cloud','4.6 LPA','Support cloud operations and internal IT workflows for business systems.',@seed_company_id),
('Fresher Jobs','Technical Associate','Flipkart','Bangalore','job','JavaScript','4.3 LPA','Assist with web product development and technical issue resolution.',@seed_company_id),

('Internship Jobs','Web Development Intern','Google','Remote','internship','HTML,CSS,JS','20,000/month','Internship focused on building landing pages and frontend components.',@seed_company_id),
('Internship Jobs','Software Engineer Intern','Microsoft','Bangalore','internship','Python','25,000/month','Work with engineering mentors on Python-based tools and services.',@seed_company_id),
('Internship Jobs','Frontend Intern','Amazon','Hyderabad','internship','React','22,000/month','Support frontend feature development using React.',@seed_company_id),
('Internship Jobs','Backend Intern','Flipkart','Bangalore','internship','Node.js','22,000/month','Build backend endpoints and support API integrations with Node.js.',@seed_company_id),
('Internship Jobs','Data Science Intern','IBM','Pune','internship','Python','24,000/month','Assist in data cleaning, analysis, and model experimentation.',@seed_company_id),
('Internship Jobs','Machine Learning Intern','Intel','Bangalore','internship','ML,Python','26,000/month','Work on ML experiments, datasets, and Python-based prototypes.',@seed_company_id),
('Internship Jobs','Android Developer Intern','Samsung','Delhi','internship','Kotlin','20,000/month','Support Android application development and testing.',@seed_company_id),
('Internship Jobs','Full Stack Intern','Zoho','Chennai','internship','MERN','22,000/month','Contribute to MERN stack features across frontend and backend.',@seed_company_id),
('Internship Jobs','DevOps Intern','Adobe','Noida','internship','Docker','24,000/month','Assist with CI/CD, Docker-based setups, and deployment workflows.',@seed_company_id),
('Internship Jobs','UI UX Intern','Paytm','Noida','internship','Figma','18,000/month','Support UI/UX design work including wireframes and high-fidelity mockups.',@seed_company_id),
('Internship Jobs','Cloud Intern','Oracle','Bangalore','internship','AWS','24,000/month','Support cloud deployment tasks and environment management.',@seed_company_id),
('Internship Jobs','Testing Intern','Infosys','Mysore','internship','Automation','18,000/month','Assist QA automation teams in writing and running test scripts.',@seed_company_id),
('Internship Jobs','React Developer Intern','Swiggy','Remote','internship','React','20,000/month','Build reusable React components and improve frontend experiences.',@seed_company_id),
('Internship Jobs','Backend Developer Intern','Razorpay','Bangalore','internship','Node','25,000/month','Support backend systems and payment service integrations.',@seed_company_id),
('Internship Jobs','Python Intern','TCS','Pune','internship','Python','18,000/month','Contribute to Python-based automation and data tasks.',@seed_company_id),

('Python Developer Jobs','Python Developer','TCS','Pune','job','Python,Django','6.0 LPA','Develop and maintain Django-based web applications.',@seed_company_id),
('Python Developer Jobs','Backend Python Engineer','Infosys','Bangalore','job','Python,Flask','6.5 LPA','Build backend APIs and microservices using Flask.',@seed_company_id),
('Python Developer Jobs','Python API Developer','Wipro','Hyderabad','job','Python,REST','6.2 LPA','Design and maintain REST APIs for internal products.',@seed_company_id),
('Python Developer Jobs','Junior Python Engineer','Accenture','Mumbai','job','Python','5.8 LPA','Support Python application development and debugging.',@seed_company_id),
('Python Developer Jobs','Python Software Developer','Capgemini','Delhi','job','Python','6.1 LPA','Work on Python-driven software features and internal systems.',@seed_company_id),
('Python Developer Jobs','Python Developer','Cognizant','Chennai','job','Python','6.0 LPA','Develop scalable backend modules using Python.',@seed_company_id),
('Python Developer Jobs','Django Developer','Zoho','Chennai','job','Django','6.3 LPA','Build business web applications using Django.',@seed_company_id),
('Python Developer Jobs','Flask Developer','IBM','Pune','job','Flask','6.2 LPA','Create lightweight APIs and services in Flask.',@seed_company_id),
('Python Developer Jobs','Python Data Engineer','Amazon','Bangalore','job','Python,ETL','7.0 LPA','Work on ETL pipelines and backend data processing systems.',@seed_company_id),
('Python Developer Jobs','Python Backend Developer','Flipkart','Bangalore','job','Python','6.7 LPA','Develop backend services and maintain Python APIs.',@seed_company_id),
('Python Developer Jobs','Python ML Engineer','Intel','Bangalore','job','ML','7.2 LPA','Build ML-backed Python services and model pipelines.',@seed_company_id),
('Python Developer Jobs','Python Automation Engineer','Oracle','Hyderabad','job','Automation','6.4 LPA','Create automation scripts for testing and infrastructure tasks.',@seed_company_id),
('Python Developer Jobs','Python API Developer','Paytm','Noida','job','REST','6.3 LPA','Build and maintain RESTful backend APIs.',@seed_company_id),
('Python Developer Jobs','Python Software Engineer','Adobe','Noida','job','Python','6.8 LPA','Develop production-ready Python applications.',@seed_company_id),
('Python Developer Jobs','Python Developer','Swiggy','Remote','job','Python','6.5 LPA','Work on remote backend engineering tasks in Python.',@seed_company_id),

('Java Developer Jobs','Java Developer','TCS','Mumbai','job','Java,Spring','6.2 LPA','Develop Java and Spring based enterprise applications.',@seed_company_id),
('Java Developer Jobs','Backend Java Engineer','Infosys','Bangalore','job','Spring Boot','6.7 LPA','Build backend services using Spring Boot.',@seed_company_id),
('Java Developer Jobs','Java Software Engineer','Wipro','Hyderabad','job','Java','6.3 LPA','Work on Java modules and enterprise software maintenance.',@seed_company_id),
('Java Developer Jobs','Junior Java Developer','Accenture','Pune','job','Java','6.0 LPA','Support development of Java applications and services.',@seed_company_id),
('Java Developer Jobs','Java API Developer','Capgemini','Delhi','job','REST','6.1 LPA','Design and maintain Java-based REST APIs.',@seed_company_id),
('Java Developer Jobs','Java Developer','IBM','Pune','job','Spring','6.5 LPA','Build scalable applications using Java and Spring.',@seed_company_id),
('Java Developer Jobs','Java Backend Engineer','Amazon','Bangalore','job','Java','7.2 LPA','Develop backend services for high-scale systems.',@seed_company_id),
('Java Developer Jobs','Java Developer','Oracle','Hyderabad','job','Java','7.0 LPA','Build enterprise-grade Java applications.',@seed_company_id),
('Java Developer Jobs','Java Microservices Developer','Adobe','Noida','job','Microservices','7.1 LPA','Work on distributed services and Java microservice architecture.',@seed_company_id),
('Java Developer Jobs','Java Developer','Flipkart','Bangalore','job','Spring','6.8 LPA','Maintain scalable Java applications with Spring.',@seed_company_id),
('Java Developer Jobs','Java Software Engineer','Paytm','Noida','job','Java','6.6 LPA','Contribute to Java backend features and support.',@seed_company_id),
('Java Developer Jobs','Java Application Developer','Intel','Bangalore','job','Java','6.9 LPA','Build Java applications for internal tooling and automation.',@seed_company_id),
('Java Developer Jobs','Java Backend Developer','Zoho','Chennai','job','Java','6.4 LPA','Work on product backend features using Java.',@seed_company_id),
('Java Developer Jobs','Java Developer','Swiggy','Remote','job','Java','6.5 LPA','Remote role focused on backend development in Java.',@seed_company_id),
('Java Developer Jobs','Java Engineer','Cognizant','Chennai','job','Java','6.3 LPA','Develop enterprise business logic using Java.',@seed_company_id),

('Full Stack Developer Jobs','Full Stack Developer','Google','Bangalore','job','MERN','12.0 LPA','Build modern full stack features using the MERN stack.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Engineer','Microsoft','Hyderabad','job','React,Node','11.5 LPA','Work across frontend and backend product modules.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Amazon','Bangalore','job','MERN','11.8 LPA','Develop end-to-end product features with JavaScript technologies.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Flipkart','Bangalore','job','MEAN','10.8 LPA','Support MEAN stack application development.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','TCS','Pune','job','React,Node','8.0 LPA','Build and maintain React and Node.js based applications.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Infosys','Mysore','job','JavaScript','8.2 LPA','Work on full stack JavaScript product development.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Zoho','Chennai','job','Node','8.4 LPA','Contribute across product UI and Node.js backend services.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','IBM','Pune','job','React','8.7 LPA','Work on business applications spanning frontend and backend.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Capgemini','Delhi','job','Angular','8.1 LPA','Support enterprise web app development across the stack.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Engineer','Oracle','Hyderabad','job','Node','9.0 LPA','Build APIs and frontend integrations for enterprise tools.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Intel','Bangalore','job','MERN','9.2 LPA','Develop MERN applications for internal platforms.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Adobe','Noida','job','React','9.5 LPA','Work across UI development and service integration.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Swiggy','Remote','job','Node','8.9 LPA','Remote full stack role focused on Node.js-based product work.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Paytm','Noida','job','React','8.8 LPA','Build user-facing features and backend integrations.',@seed_company_id),
('Full Stack Developer Jobs','Full Stack Developer','Cognizant','Chennai','job','JavaScript','8.0 LPA','Develop full stack business solutions with JavaScript.',@seed_company_id),

('Frontend Developer Jobs','Frontend Developer','Google','Bangalore','job','React','10.5 LPA','Build high-quality frontend interfaces using React.',@seed_company_id),
('Frontend Developer Jobs','Frontend Engineer','Microsoft','Hyderabad','job','React','10.2 LPA','Develop frontend experiences for enterprise products.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Amazon','Bangalore','job','HTML,CSS,JS','9.8 LPA','Create responsive frontend components and web pages.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Flipkart','Bangalore','job','Angular','9.5 LPA','Work on Angular-based e-commerce frontend modules.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','TCS','Pune','job','React','7.2 LPA','Build scalable React frontends for internal clients.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Infosys','Mysore','job','JavaScript','7.0 LPA','Support UI development and frontend testing.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Zoho','Chennai','job','Vue','7.5 LPA','Create product UIs using Vue and modern frontend tooling.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','IBM','Pune','job','React','8.0 LPA','Contribute to frontend architecture and component systems.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Capgemini','Delhi','job','Angular','7.8 LPA','Work on frontend modules and enterprise UI flows.',@seed_company_id),
('Frontend Developer Jobs','Frontend Engineer','Oracle','Hyderabad','job','React','8.6 LPA','Develop web frontend experiences for internal platforms.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Intel','Bangalore','job','HTML','7.4 LPA','Work on frontend markup and UI enhancements.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Adobe','Noida','job','CSS','8.2 LPA','Support web UI styling and frontend interaction work.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Swiggy','Remote','job','React','8.4 LPA','Remote frontend development with React-based applications.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Paytm','Noida','job','JavaScript','7.9 LPA','Build frontend features and interactive dashboards.',@seed_company_id),
('Frontend Developer Jobs','Frontend Developer','Cognizant','Chennai','job','HTML','7.1 LPA','Support frontend implementation and optimization tasks.',@seed_company_id),

('UI/UX Jobs','UI Designer','Google','Bangalore','job','Figma','9.0 LPA','Create polished UI layouts and visual systems using Figma.',@seed_company_id),
('UI/UX Jobs','UX Designer','Microsoft','Hyderabad','job','UX Research','9.3 LPA','Conduct user research and improve digital product flows.',@seed_company_id),
('UI/UX Jobs','Product Designer','Amazon','Bangalore','job','UI','9.8 LPA','Design user-centered product journeys and interfaces.',@seed_company_id),
('UI/UX Jobs','UI UX Designer','Flipkart','Bangalore','job','Figma','8.8 LPA','Work on app and web UI/UX designs for customer products.',@seed_company_id),
('UI/UX Jobs','UI Designer','Paytm','Noida','job','Design','8.2 LPA','Create user interface assets and design systems.',@seed_company_id),
('UI/UX Jobs','UX Designer','Adobe','Noida','job','UX','9.4 LPA','Improve usability and user experience of digital products.',@seed_company_id),
('UI/UX Jobs','UI Designer','TCS','Pune','job','Figma','7.2 LPA','Design enterprise dashboards and interface assets.',@seed_company_id),
('UI/UX Jobs','UX Designer','Infosys','Mysore','job','UX','7.4 LPA','Support user journey improvements and prototype validation.',@seed_company_id),
('UI/UX Jobs','UI Designer','Zoho','Chennai','job','Design','7.8 LPA','Create interface concepts and component visuals.',@seed_company_id),
('UI/UX Jobs','UX Designer','IBM','Pune','job','UX Research','8.5 LPA','Research user behavior and suggest product improvements.',@seed_company_id),
('UI/UX Jobs','UI Designer','Capgemini','Delhi','job','UI','7.6 LPA','Design web interfaces and maintain design consistency.',@seed_company_id),
('UI/UX Jobs','UX Designer','Oracle','Hyderabad','job','UX','8.3 LPA','Improve application usability and workflow efficiency.',@seed_company_id),
('UI/UX Jobs','UI Designer','Intel','Bangalore','job','Figma','8.0 LPA','Build design mockups and high-fidelity UI screens.',@seed_company_id),
('UI/UX Jobs','UX Designer','Swiggy','Remote','job','UX','8.1 LPA','Remote UX role focused on consumer product experiences.',@seed_company_id),
('UI/UX Jobs','UI Designer','Cognizant','Chennai','job','Design','7.5 LPA','Support interface design and visual quality improvements.',@seed_company_id)
;
